import { GoogleGenAI, GenerateContentResponse, Modality, VideosOperationResponse } from "@google/genai";

if (!process.env.API_KEY) {
  console.warn(
    "API_KEY environment variable not set. App may not function correctly."
  );
}

const getAiClient = () => new GoogleGenAI({ apiKey: process.env.API_KEY });

interface GenerateContentStreamParams {
  prompt: string;
  location?: { latitude: number; longitude: number };
  systemInstruction?: string;
}

export async function* generateContentStream({ prompt, location, systemInstruction }: GenerateContentStreamParams): AsyncGenerator<GenerateContentResponse> {
  const ai = getAiClient();
  const model = 'gemini-2.5-pro';
  
  const config: any = {
    tools: [{ googleSearch: {} }, { googleMaps: {} }],
    thinkingConfig: { thinkingBudget: 32768 },
  };

  if (systemInstruction) {
    config.systemInstruction = systemInstruction;
  }
  
  if (location) {
    config.toolConfig = {
      retrievalConfig: {
        latLng: {
          latitude: location.latitude,
          longitude: location.longitude,
        },
      },
    };
  }

  const responseStream = await ai.models.generateContentStream({
    model,
    contents: prompt,
    config,
  });

  for await (const chunk of responseStream) {
    yield chunk;
  }
}

// --- Media Suite Services ---

// Image Generation
export async function generateImage(prompt: string, aspectRatio: string): Promise<string> {
    const ai = getAiClient();
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
            numberOfImages: 1,
            outputMimeType: 'image/jpeg',
            aspectRatio: aspectRatio as "1:1" | "3:4" | "4:3" | "9:16" | "16:9",
        },
    });

    const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
    return `data:image/jpeg;base64,${base64ImageBytes}`;
}


// Image Editing
export async function editImage(prompt: string, imageBase64: string, mimeType: string): Promise<string> {
    const ai = getAiClient();
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                { inlineData: { data: imageBase64, mimeType } },
                { text: prompt },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            const base64ImageBytes: string = part.inlineData.data;
            return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
        }
    }
    throw new Error("No image was generated by the model.");
}

// Image Analysis
export async function analyzeImage(prompt: string, imageBase64: string, mimeType: string): Promise<string> {
    const ai = getAiClient();
    const imagePart = {
        inlineData: {
            mimeType,
            data: imageBase64,
        },
    };
    const textPart = { text: prompt };

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: { parts: [imagePart, textPart] },
    });
    
    return response.text;
}


// Video Generation
export async function generateVideo(prompt: string, aspectRatio: string, startImage?: { base64: string; mimeType: string }): Promise<VideosOperationResponse> {
    const ai = getAiClient();
    let imagePayload;
    if (startImage) {
        imagePayload = {
            imageBytes: startImage.base64,
            mimeType: startImage.mimeType,
        };
    }

    let operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt: prompt,
        image: imagePayload,
        config: {
            numberOfVideos: 1,
            resolution: '720p',
            aspectRatio: aspectRatio as "16:9" | "9:16",
        }
    });
    return operation;
}

export async function pollVideoOperation(operation: VideosOperationResponse): Promise<VideosOperationResponse> {
    const ai = getAiClient();
    let polledOperation = operation;
    while (!polledOperation.done) {
        await new Promise(resolve => setTimeout(resolve, 10000));
        polledOperation = await ai.operations.getVideosOperation({ operation: polledOperation });
    }
    return polledOperation;
}

// Text-to-Speech
export async function generateSpeech(text: string): Promise<string> {
    const ai = getAiClient();
    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-preview-tts",
        contents: [{ parts: [{ text }] }],
        config: {
            responseModalities: [Modality.AUDIO],
            speechConfig: {
                voiceConfig: {
                    prebuiltVoiceConfig: { voiceName: 'Kore' },
                },
            },
        },
    });

    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (base64Audio) {
        return `data:audio/mpeg;base64,${base64Audio}`;
    }
    throw new Error("No audio was generated.");
}